language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install -U nose
  - if ! [[ $TRAVIS_PYTHON_VERSION > '2.6' ]]; then pip install unittest2 ; fi
  - if [[ $TRAVIS_PYTHON_VERSION > '3.' ]]; then pip install numpy ; fi
  - pip install --install-option="--no-cython-compile" cython
  - pip install coverage
  - pip install coveralls
  - python setup.py develop
before_script:
  - mkdir testrunner
  - cp .coveragerc testrunner/
  - cd testrunner
script:
  - coverage run -m nose.core traits --exe
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
